[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
testpaths = ["tests"]
pythonpath = ["python/lambda", "python"]
[tool.pyright]
exclude = ["**/cdk.out", "**/node_modules", "**/venv", "**/__pycache__", "**/.*"]