"""Added to Article

Revision ID: 1b275c0f7d6d
Revises: 1b5a670e0049
Create Date: 2024-04-23 15:40:56.928304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b275c0f7d6d'
down_revision: Union[str, None] = '1b5a670e0049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('_image', sa.String(), nullable=True))
    op.add_column('article', sa.Column('_source_navlog', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', '_source_navlog')
    op.drop_column('article', '_image')
    # ### end Alembic commands ###
