"""Added logged_at for theme

Revision ID: 1b5a670e0049
Revises: d500a52e11b0
Create Date: 2024-04-22 10:56:45.608900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5a670e0049'
down_revision: Union[str, None] = 'd500a52e11b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('_logged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', '_logged_at')
    # ### end Alembic commands ###
