"""Add to ThemeType Enum

Revision ID: 6d058eb8be47
Revises: 1b275c0f7d6d
Create Date: 2024-04-23 20:37:56.643162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d058eb8be47"
down_revision: Union[str, None] = "1b275c0f7d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TYPE themetype ADD VALUE IF NOT EXISTS 'RECURRENT'")
    op.execute("ALTER TYPE themetype ADD VALUE IF NOT EXISTS 'SPORADIC'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
