"""Add article tab_id

Revision ID: 761dee54e82d
Revises: 82e350e3f3fd
Create Date: 2024-05-28 13:49:07.373607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761dee54e82d'
down_revision: Union[str, None] = '82e350e3f3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('_tab_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', '_tab_id')
    # ### end Alembic commands ###
