"""Add to ThemeType Enum

Revision ID: 82725af4a9ce
Revises: 6d058eb8be47
Create Date: 2024-04-24 10:38:44.734273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82725af4a9ce'
down_revision: Union[str, None] = '6d058eb8be47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
