"""Add Theme embedding

Revision ID: 82e350e3f3fd
Revises: bde4990708ab
Create Date: 2024-05-27 10:38:56.491358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "82e350e3f3fd"
down_revision: Union[str, None] = "bde4990708ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("theme", sa.Column("_embedding", Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("theme", "_embedding")
    # ### end Alembic commands ###
