"""add type to Article

Revision ID: c08bec3c2cba
Revises: 77e138b9dcaf
Create Date: 2024-10-03 14:13:40.606486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c08bec3c2cba"
down_revision: Union[str, None] = "77e138b9dcaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE articletype AS ENUM ('ARTICLE', 'SEARCH_RESULT')")
    op.add_column(
        "article",
        sa.Column(
            "_type",
            sa.Enum("ARTICLE", "SEARCH_RESULT", name="articletype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article", "_type")
    # ### end Alembic commands ###
