"""add browse and browsed

Revision ID: c4796d9139b9
Revises: d942e41d43bc
Create Date: 2024-08-16 12:50:39.375669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4796d9139b9'
down_revision: Union[str, None] = 'd942e41d43bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browse',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_title', sa.String(), nullable=True),
    sa.Column('_created_at', sa.DateTime(), nullable=True),
    sa.Column('_updated_at', sa.DateTime(), nullable=True),
    sa.Column('_logged_at', sa.DateTime(), nullable=True),
    sa.Column('_tab_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_browse__logged_at'), 'browse', ['_logged_at'], unique=False)
    op.create_index(op.f('ix_browse__tab_id'), 'browse', ['_tab_id'], unique=True)
    op.create_table('browsed',
    sa.Column('_article_id', sa.UUID(), nullable=False),
    sa.Column('_browse_id', sa.UUID(), nullable=False),
    sa.Column('_count', sa.Integer(), nullable=True),
    sa.Column('_time', sa.Integer(), nullable=True),
    sa.Column('_created_at', sa.DateTime(), nullable=True),
    sa.Column('_logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['_article_id'], ['article._id'], ),
    sa.ForeignKeyConstraint(['_browse_id'], ['browse._id'], ),
    sa.PrimaryKeyConstraint('_article_id', '_browse_id')
    )
    op.create_index(op.f('ix_browsed__logged_at'), 'browsed', ['_logged_at'], unique=False)
    op.drop_column('article', '_tab_id')
    op.drop_column('article', '_document_id')
    op.drop_column('article', '_parent_document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('_parent_document_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('_document_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('_tab_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_browsed__logged_at'), table_name='browsed')
    op.drop_table('browsed')
    op.drop_index(op.f('ix_browse__tab_id'), table_name='browse')
    op.drop_index(op.f('ix_browse__logged_at'), table_name='browse')
    op.drop_table('browse')
    # ### end Alembic commands ###
