"""_avg_article_distance to theme

Revision ID: d942e41d43bc
Revises: 080b641437ee
Create Date: 2024-08-15 09:44:28.091143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd942e41d43bc'
down_revision: Union[str, None] = '080b641437ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('_avg_article_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', '_avg_article_distance')
    # ### end Alembic commands ###
