Name: onPushToMainDeploymentWorkflow
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Actions:
  BackendTest:
    Identifier: aws/managed-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        IncludePaths:
          - "**/*"
        ExcludePaths:
          - "*/.aws/workflows/*"
        ReportNamePrefix: AutoDiscovered
        Enabled: true
    Configuration:
      Steps:
        - Run: pip install -r requirements.txt
        - Run: pytest --junitxml=test_unit_results.xml --cov-report xml:test_unit_coverage.xml --cov=. tests/unit
        - Run: echo "No test coverage step"
  BackendCDKBootstrapAction:
    Identifier: aws/cdk-bootstrap@v1
    Compute:
      Type: Lambda
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: us-west-2
    Environment:
      Name: default_environment
      Connections:
        - Name: "559845934392"
          Role: CodeCatalystWorkflowDevelopmentRole-dassie
  BackendCDKDeploy:
    Identifier: aws/cdk-deploy@v1
    Compute:
      Type: EC2
    Inputs:
      Sources:
        - WorkflowSource
    DependsOn:
      - BackendCDKBootstrapAction
      - BackendTest
    Configuration:
      StackName: TodoAppBackendStack-nwbxl
      Region: us-west-2
      Context: '{"stack_name": "TodoAppBackendStack-nwbxl"}'
    Environment:
      Name: default_environment
      Connections:
        - Name: "559845934392"
          Role: CodeCatalystWorkflowDevelopmentRole-dassie
